### ISSUE TITLE
Updates for drugFromSource and drugFromSourceId to support drug combinations

### ISSUE THREAD

**Issue by apriltuesday** [EBIvariation/opentargets-pharmgkb#40]
As discussed in [22 April meeting](https://docs.google.com/document/d/1_ayBXr2Q-4z0nxCpCi5L7SfzoDi0OPsp_KIBBRYe7vI/edit#heading=h.8jl5utc0yth3), we should make the attribute `drugFromSource` a list when split on `/` only (other delimiters have a different semantic in PGKB and should continue to be exploded into separate evidence) and rename the attribute to be plural `drugsFromSource`.

This is to support drug combinations like [ivacaftor / lumacaftor](https://www.pharmgkb.org/chemical/PA166152935).

To remove complexity and because CHEBI IDs aren't being used by OT, we will remove the `drugFromSourceId` attribute entirely.

Related OT issue [here](https://github.com/opentargets/issues/issues/3205).

**Comment by ireneisdoomed** [comment]
After a discussion with [@DSuveges](https://github.com/DSuveges) we have agreed that the most accurate solution is to create a `drugs` object. This will be a list of structs with 2 keys:

`drugFromSource`: name of the drug at source
`drugId`: CHEMBL ID that will be populated by us later on in the drug mapping step, so it will be null in your case

This solution solves the problem of keeping the parity between name and ID. Now that CHEBIs have been removed, you are not affected by this, but it is important for us so that we can map each drug name to the CHEMBL ID after it is mapped.

Thank you very much! Please let us know of any issues
